#ifndef __dz_djalel_LO_CiteQuranOXT_CiteQuranOXT_idl__
#define __dz_djalel_LO_CiteQuranOXT_CiteQuranOXT_idl__

#include <com/sun/star/task/XJobExecutor.idl>
module dz { module djalel { module LO { module CiteQuranOXT {

	service ShowIQTDialog : com::sun::star::task::XJobExecutor {

	};

	service ShowAboutDialog : com::sun::star::task::XJobExecutor {

	};
 }; }; }; };
 
#endif
